vars:
  output_dir: /mnt/shared-storage-user/leihaodi/diffusion/dflash/sglang-logs-final/4-gpu

jobs:
  - name: gpu0
    gpu: 0
    target_model: /mnt/shared-storage-user/p1-shared/Qwen/Qwen3-30B-A3B-Thinking-2507
    draft_model: /mnt/shared-storage-user/leihaodi/opd/verl/checkpoints/verl-dflash-opd/a3b-2node-forward/student-14-teacher-2-05-10/bsz-28-micro-1/train-mathcode16k_mbpp_user_prompt/global_step_3000/draft_model
    output_md: ${output_dir}/gpu0.md
    dataset_name: &eval_datasets ["gsm8k:128", "aime24:30", "aime25:30", "math500:128", "mbpp:128", "humaneval:128", "mt-bench:80", "mgsm_zh:32", "swe-bench:128", "alpaca:128", "aime26:30"]
    concurrency_num: 1
    add_base: false
    enable_think: true
    attention_backends: fa3
    max_new_tokens: 8192

  - name: gpu1
    gpu: 1
    target_model: /mnt/shared-storage-user/p1-shared/Qwen/Qwen3-30B-A3B-Thinking-2507
    draft_model: /mnt/shared-storage-user/leihaodi/opd/verl/checkpoints/verl-dflash-opd/a3b-2node-forward/student-14-teacher-2-05-10/bsz-28-micro-1/train-mathcode16k_mbpp_user_prompt/global_step_3500/draft_model
    output_md: ${output_dir}/gpu1.md
    dataset_name: *eval_datasets
    concurrency_num: "1"
    enable_think: true
    attention_backends: fa3
    max_new_tokens: 8192

  # - name: gpu2
  #   gpu: 2
  #   target_model: /mnt/shared-storage-user/p1-shared/Qwen/Qwen3-30B-A3B-Thinking-2507
  #   draft_model: /mnt/shared-storage-user/leihaodi/opd/verl/checkpoints/verl-dflash-opd/a3b-2node-forward/student-14-teacher-2-05-10/bsz-28-micro-1/train-mathcode16k_mbpp_user_prompt/global_step_2500/draft_model
  #   output_md: ${output_dir}/gpu2.md
  #   dataset_name: *eval_datasets
  #   concurrency_num: "1"
  #   enable_think: true
  #   attention_backends: fa3
  #   max_new_tokens: 8192

  # - name: gpu3
  #   gpu: 3
  #   target_model: /mnt/shared-storage-user/p1-shared/Qwen/Qwen3-30B-A3B-Thinking-2507
  #   draft_model: /mnt/shared-storage-user/leihaodi/opd/verl/checkpoints/verl-dflash-opd/a3b-2node-forward/student-14-teacher-2-05-10/bsz-28-micro-1/train-mathcode16k_mbpp_user_prompt/global_step_2000/draft_model
  #   output_md: ${output_dir}/gpu3.md
  #   dataset_name: *eval_datasets
  #   concurrency_num: "1"
  #   enable_think: true
  #   attention_backends: fa3
  #   max_new_tokens: 8192
